dtb-$(CONFIG_MACH_XIAOMI_D5X) += polaris/polaris-mp-v2.1.dtb
dtb-$(CONFIG_MACH_XIAOMI_E1N) += dipper/dipper-mp-v2.1.dtb
dtb-$(CONFIG_MACH_XIAOMI_E10) += beryllium/beryllium-mp-v2.1.dtb
dtb-$(CONFIG_MACH_XIAOMI_E1S) += equuleus/equuleus-mp-v2.1.dtb
dtb-$(CONFIG_MACH_XIAOMI_E8) += ursa/ursa-mp-v2.1.dtb
dtb-$(CONFIG_MACH_XIAOMI_E5) += perseus/perseus-mp-v2.1.dtb



always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
